fitbit-PointTracker/config/routes.rb
Rails.application.routes.draw do

	
  root 'sessions#splash'

  get 'sessions/about'
  get 'sessions/index'
  get 'sessions/profile'
  get 'sessions/otherusers'
  
  get   '/login', :to => 'sessions#new', :as => :login
	match '/auth/fitbit/callback', :to => 'sessions#create' , :via => [:get], :as => 'sessions_create'
	match '/auth/failure', :to => 'sessions#failure', :via => [:get], :as => 'sessions_failure'
  

end

fitbit-PointTracker/app/models/authorization.rb
class Authorization < ActiveRecord::Base
	belongs_to :user
  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider


def self.find_from_hash(hash)
  find_by_provider_and_uid(hash['provider'], hash['uid'])
end

def self.create_from_hash(hash, user = nil)
  user = User.create_from_hash!(hash)
  Authorization.create(:user => user, :uid => hash['uid'], :provider => hash['provider'], :token => hash['credentials']['token'], :secret => hash['credentials']['secret'])
end
end

fitbit-PointTracker/app/models/user.rb
class User < ActiveRecord::Base
	has_many :authorizations

	def self.create_from_hash!(hash)
	 	 client ||= Fitgem::Client.new(
				:consumer_key => '17e009f76e454acda410d3dbeb59d047',
				:consumer_secret => '1db1d74a7ecb4e97aa426fa42126edd1',
				:token => hash['credentials']['token'],
				:secret => hash['credentials']['secret'],
				:user_id => hash['uid'],
				:ssl => true
			)
		userinfo = client.user_info['user']
		create(:name => userinfo['fullName'])
		#create(:name => hash['uid']+hash['provider'])
	end
end

fitbit-PointTracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protected

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def signed_in?
    !!current_user
  end

  helper_method :current_user, :signed_in?

  def current_user=(user)
    @current_user = user
    #session[:user_id] = user.name
  end
end

fitbit-PointTracker/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
@@pic =''
@@GlobalAuth
	 def new
	 end
 
	def create
		auth = request.env['omniauth.auth']
		
		unless @auth = Authorization.find_from_hash(auth)
			# Create a new user or add an auth to existing user, depending on
			# whether there is already a user signed in.
			@auth = Authorization.create_from_hash(auth)
			
			
		end
		@@GlobalAuth ||= @auth
		redirect_to "/sessions/index"
	end
	def splash
		@isNotSplash = false
	end

	def failure
	
	end
	def index
		@isNotSplash = true
		@taskstandings = true
		# Log the authorizing user in.
		auth = @@GlobalAuth
		info = get_userInfo(auth)

		self.current_user = auth.user
		activities = get_activities(auth)
		pointsum = 0
		steps = 0
		lightlyActive = activities['summary']['distances'][5]['distance'].to_i
		moderatlyActive = activities['summary']['distances'][4]['distance'].to_i
		veryActive = activities['summary']['distances'][3]['distance'].to_i
		steps += activities['summary']['steps'].to_i
	
		if steps>1000
			pointsum += 100
		end
		if steps>5000
			pointsum += 500
		end
		if steps>10000
			pointsum += 1000	
		end
		if lightlyActive > 1
			pointsum += 50
		end
		if lightlyActive > 5
			pointsum += 250
		end
		if lightlyActive > 10
			pointsum += 500
		end
		if moderatlyActive > 1
			pointsum += 100
		end
		if moderatlyActive > 5
			pointsum += 500
		end
		if moderatlyActive > 5
			pointsum += 1000
		end
		if veryActive > 1
			pointsum += 200
		end
		if veryActive > 5
			pointsum += 1000
		end
		if veryActive > 10
			pointsum += 2000
		end



		@user = User.find_by(name: info['fullName']).update_attribute(:points, pointsum)
		@points = pointsum

		@users = User.order(points: :desc).limit(10)
		@count = 1
	end
	
	def about 
		@isNotSplash = true
	end
	
	def profile
		@isNotSplash = true
		info = get_userInfo(@@GlobalAuth)
		@pic = info['avatar']
		@name = info['fullName']
		@user = User.find_by(name: info['fullName'])
		@points = @user.points

		users = User.order(points: :desc)
		count = 1
		@standing = 20

		users.each do |user|
			if user.name == @name
 				@standing = count
			end

			count = count + 1
		end
	end

	def otherusers
		@isNotSplash = true
		info = get_userInfo(@@GlobalAuth)
		name = info['fullName']
		@users = User.where.not(name: name)
	end
	def connect(auth)
			client ||= Fitgem::Client.new(
				:consumer_key => '17e009f76e454acda410d3dbeb59d047',
				:consumer_secret => '1db1d74a7ecb4e97aa426fa42126edd1',
				:token => auth.token,
				:secret => auth.secret,
				:user_id => auth.uid,
				:ssl => true
			)
			return client
	end 

private
	def get_activities(auth)
		client = self.connect(auth)
		activities = client.activities_on_date('today')
		return activities
	end
	def get_userInfo(auth)
		client = self.connect(auth)
		userinfo = client.user_info['user']
		return userinfo
	end
end

fitbit-PointTracker/app/controllers/users_controller.rb
class UsersController < ApplicationController
end

fitbit-PointTracker/app/helpers/sessions_helper.rb
module SessionsHelper
end

fitbit-PointTracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FitbitPointtracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag     'style', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container-fluid page">
	    <header role="banner" class="navbar navbar-fixed-top navbar-inverse">
        <% if @isNotSplash %>
	      <div class="container">
	        <div class="navbar-header">
	          <button data-toggle="collapse-side" data-target=".side-collapse" data-target-2=".side-collapse-container" type="button" class="navbar-toggle pull-left">
	          	<span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
	          </button>
	          <% if @taskstandings %>
				<div class="toggle-tasks-standings"></div> 
				  <% end %>
	        </div>
	        <div class="navbar-inverse side-collapse in">
	          <nav role="navigation" class="navbar-collapse">
	            <ul class="nav navbar-nav">
	              <li><%= link_to "Home", sessions_index_path %></li>
	              <li><%= link_to "Profile", sessions_profile_path %></li>
	              <li><%= link_to "Other Users", sessions_otherusers_path %></li>
	              <li><%= link_to "About", sessions_about_path %></li>
	            </ul>
	          </nav>
	        </div>
	      </div>
        <% end %>
	    </header>
	<%= yield %>
	</div>
</body>
<script>
    $(document).ready(function() {   
            var sideslider = $('[data-toggle=collapse-side]');
            var sel = sideslider.attr('data-target');
            var sel2 = sideslider.attr('data-target-2');
            sideslider.click(function(event){
                $(sel).toggleClass('in');
                $(sel2).toggleClass('out');
            });
            $('.toggle-tasks-standings').html('Tasks');
            var standings_height = $('.standings').height();
            $('.tasks').css({
              "margin-top" : standings_height - (2 * standings_height)
            });
            $('.toggle-tasks-standings').click(function(){
                if($('.standings').hasClass('in')){
                  $('.standings').removeClass('in');
                  $('.tasks').addClass('in');
                  $('.toggle-tasks-standings').html('Standings');
                }
                else{
                  $('.tasks').removeClass('in');
                  $('.standings').addClass('in');
                  $('.toggle-tasks-standings').html('Tasks');
                }
            });
        });
</script>
</html>